#%test.quarkus.datasource.jdbc.url=

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=sam
quarkus.datasource.password=s4mP@ssword
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/sam_music
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-envers.audit-strategy=org.hibernate.envers.strategy.ValidityAuditStrategy

# testing
quarkus.datasource.devservices.port=15432
quarkus.datasource.devservices.db-name=sam_music
quarkus.datasource.devservices.username=sam
quarkus.datasource.devservices.password=s4mP@ssword