@startuml
entity SheetEntity {
    * id
}

entity ScoreEntity {
    * id
}

entity GenreEntity {
    * id
}

entity SheetCollectionEntity {
    * id
}

entity CollectionSheetEntity {
    * id
}

SheetEntity }o--|| GenreEntity
SheetEntity }|--|{ ScoreEntity
CollectionSheetEntity ||--|{ SheetEntity
SheetCollectionEntity }|--|{ CollectionSheetEntity
@enduml