@startuml
entity SheetEntity {
    * id
}

entity ScoreEntity {
    * id
}

entity SheetCollectionEntity {
    * id
}

entity CollectionSheetEntity {
    * id
}

SheetEntity }|--|{ ScoreEntity
CollectionSheetEntity ||--|{ SheetEntity
SheetCollectionEntity }|--|{ CollectionSheetEntity
@enduml